#!/bin/bash

set -euo pipefail
shopt -s inherit_errexit

aggregate() {
    local sum=''
    while read -r line; do
        if [ -z "$line" ]; then
            if [ -n "$sum" ]; then
                echo "$sum"
                sum=''
            fi
        else
            if [ -z "$sum" ]; then
                sum=0
            fi
            sum="$(( sum + line ))"
        fi
    done
    if [ -n "$sum" ]; then
        echo "$sum"
    fi
}

max_n() {
    local n="$1"
    aggregate | sort -nr | head -n "$n"
}

part1() {
    max_n 1
}

part2() {
    local result=0
    while read -r line; do
        result="$(( result + line ))"
    done < <(max_n 3)
    echo "$result"
}

if [ -z "${TEST:-}" ]; then
    solution1="$(<./inputs/day1 part1)"
    ( set -x; (( solution1 == 71023 )) )

    solution2="$(<./inputs/day1 part2)"
    ( set -x; (( solution2 == 206289 )) )
else
    test1="$(<./test-inputs/day1 part1)"
    ( set -x; (( test1 == 7000 + 8000 + 9000 )) )

    test2="$(<./test-inputs/day1 part2)"
    ( set -x; (( test2 == 24000 + 11000 + 10000 )) )
fi
