#!/bin/bash

set -euo pipefail
shopt -s inherit_errexit

run() {
    reverse_when_pushing="$1"

    IFS='' read -r line

    local num_stacks="$(( (${#line} + 1) / 4 ))"
    local stacks=()

    while :; do
        for (( stack=0; stack < num_stacks; stack++ )); do
            local box="${line:$(( stack * 4 + 1 )):1}"
            if [ "${box[0]}" != ' ' ]; then
                stacks["$stack"]="$box${stacks["$stack"]:-}"
            fi
        done

        IFS='' read -r line
        if [ -z "$line" ]; then
            break
        fi
    done

    while read -r _move n _from stack_start _to stack_end; do
        stack_start="$(( stack_start - 1 ))"

        stack_end="$(( stack_end - 1 ))"

        if [ "$reverse_when_pushing" == '1' ]; then
            for (( i=0; i < n; i++ )); do
                local stack="${stacks[$stack_start]}"
                local box="${stack: -1}"
                stacks[$stack_start]="${stack:0:$(( ${#stack} - 1 ))}"
                stacks[$stack_end]+="$box"
            done
        else
            local stack="${stacks[$stack_start]}"
            local start="$(( ${#stack} - n ))"
            local boxes="${stack:$start:$n}"
            stacks[$stack_start]="${stack:0:$start}"
            stacks[$stack_end]+="$boxes"
        fi
    done

    local result=''
    for stack in "${stacks[@]}"; do
        result+="${stack: -1}"
    done
    echo "$result"
}

part1() {
    run 1
}

part2() {
    run 0
}

if [ -z "${TEST:-}" ]; then
    solution1="$(<./inputs/day5 part1)"
    ( set -x; [ "$solution1" == 'VJSFHWGFT' ] )

    solution2="$(<./inputs/day5 part2)"
    ( set -x; [ "$solution2" == 'LCTQFBVZV' ] )
else
    test1="$(<./test-inputs/day5 part1)"
    ( set -x; [ "$test1" == 'CMZ' ] )

    test2="$(<./test-inputs/day5 part2)"
    ( set -x; [ "$test2" == 'MCD' ] )
fi
